[ansible]

# Only test against the two most recent Python and ansible-core releases.
skip =
    py3.7
    py3.8
    py3.9
    py3.10
    py3.11
    py3.12
    2.9
    2.10
    2.11
    2.12
    2.13
    2.14
    2.15
    2.16
    2.17
    2.18
    devel
    milestone
