---
galaxy_info:
  author: Project Potos
  description: Role to manage wallpapers of Potos Linux Clients.
  company: potos
  license: GPL-3.0-only
  min_ansible_version: "2.14"
  platforms:
    - name: Fedora
      versions:
        - all
  galaxy_tags:
    - potos
    - wallpaper

dependencies: []
