---
dependency:
  name: galaxy

driver:
  name: podman

platforms:
  - name: potos-wallpaper
    image: "ghcr.io/projectpotos/docker-${MOLECULE_DISTRO:-fedora44}-ansible:latest"
    pre_build_image: true
    override_command: false
    privileged: false
    systemd: true

provisioner:
  name: ansible

verifier:
  name: ansible
